openapi: 3.0.0
info:

  version: 1.0

  title: small unit test

  description: small unit test

paths:

  /dummy:

    post:
      responses:
        '201':
          description: created
          
components:

  schemas:
    
    Dummy:
      type: string

