openapi: 3.0.0
info:

  version: 1.0

  title: Small test

  description: Used to isolate small fragments for testing

paths:
  /dummy:

    get:
      responses:
        '200':
          description: ok
          
    
components:

  schemas:

    Dummy:
      type: string
      
    EnumOfObjects:
      enum:
        - id: 1
          name: LoL
          slug: league-of-legends
        - id: 3
          name: CS:GO
          slug: cs-go
      type: object      
      
