#!/bin/bash
echo codegen "$@" 
codegen $1 $2 $3 $4 $5 &>/tmp/output 
RETURN=$?
if [ $RETURN -eq 0 ]
then
  temp=`tail -1 /tmp/output`
  cd $temp && mvnd compile -B
  exit $?
else
  echo GENERATOR FAILURE
  cat /tmp/output
  exit $RETURN
fi
