#!/bin/bash
echo codegen $1
codegen $1 &>/tmp/output 
RETURN=$?
if [ $RETURN -eq 0 ]
then
  temp=`tail -1 /tmp/output`
  cd $temp && mvnd compile -B
  exit $?
else
  echo GENERATOR FAILURE
  cat /tmp/output
  exit $RETURN
fi
