#!/bin/bash
mkdir -p ../src/docs
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/main/schema/Car.java ../src/docs/ 
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/main/schema/Bike.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/main/schema/Vehicle.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/main/schema/Geometry.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/main/schema/Circle.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/main/schema/Rectangle.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/main/schema/PetSearch.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/main/schema/PetByAge.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/main/schema/PetByType.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/main/schema/Pet3.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/main/schema/Cat3.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/main/schema/Dog3.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/main/schema/ReadOnly.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/main/schema/WriteOnly.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/library/client/Client.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/library/service/Service.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/library/service/ServiceController.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/library/schema/Book.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/library/schema/User.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/library/schema/Language.java ../src/docs/
cp target/generated-sources/java/org/davidmoten/oa3/codegen/test/paths/path/UploadPostRequestMultipartFormData.java ../src/docs/
